/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as CriptoRouteImport } from './routes/cripto'
import { Route as DonarRouteImport } from './routes/donar'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as IaRouteImport } from './routes/ia'
import { Route as InversionRouteImport } from './routes/inversion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ResistenciaRouteImport } from './routes/resistencia'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const CriptoRoute = CriptoRouteImport.update({
  id: '/cripto',
  path: '/cripto',
  getParentRoute: () => rootRouteImport,
} as any)
const DonarRoute = DonarRouteImport.update({
  id: '/donar',
  path: '/donar',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const InversionRoute = InversionRouteImport.update({
  id: '/inversion',
  path: '/inversion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ResistenciaRoute = ResistenciaRouteImport.update({
  id: '/resistencia',
  path: '/resistencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comunidad': typeof ComunidadRoute
  '/cripto': typeof CriptoRoute
  '/donar': typeof DonarRoute
  '/eventos': typeof EventosRoute
  '/ia': typeof IaRoute
  '/inversion': typeof InversionRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/resistencia': typeof ResistenciaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comunidad': typeof ComunidadRoute
  '/cripto': typeof CriptoRoute
  '/donar': typeof DonarRoute
  '/eventos': typeof EventosRoute
  '/ia': typeof IaRoute
  '/inversion': typeof InversionRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/resistencia': typeof ResistenciaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comunidad': typeof ComunidadRoute
  '/cripto': typeof CriptoRoute
  '/donar': typeof DonarRoute
  '/eventos': typeof EventosRoute
  '/ia': typeof IaRoute
  '/inversion': typeof InversionRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/resistencia': typeof ResistenciaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/comunidad'
    | '/cripto'
    | '/donar'
    | '/eventos'
    | '/ia'
    | '/inversion'
    | '/login'
    | '/panel'
    | '/perfil'
    | '/registro'
    | '/resistencia'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/comunidad'
    | '/cripto'
    | '/donar'
    | '/eventos'
    | '/ia'
    | '/inversion'
    | '/login'
    | '/panel'
    | '/perfil'
    | '/registro'
    | '/resistencia'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/comunidad'
    | '/cripto'
    | '/donar'
    | '/eventos'
    | '/ia'
    | '/inversion'
    | '/login'
    | '/panel'
    | '/perfil'
    | '/registro'
    | '/resistencia'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ComunidadRoute: typeof ComunidadRoute
  CriptoRoute: typeof CriptoRoute
  DonarRoute: typeof DonarRoute
  EventosRoute: typeof EventosRoute
  IaRoute: typeof IaRoute
  InversionRoute: typeof InversionRoute
  LoginRoute: typeof LoginRoute
  PanelRoute: typeof PanelRoute
  PerfilRoute: typeof PerfilRoute
  RegistroRoute: typeof RegistroRoute
  ResistenciaRoute: typeof ResistenciaRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cripto': {
      id: '/cripto'
      path: '/cripto'
      fullPath: '/cripto'
      preLoaderRoute: typeof CriptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donar': {
      id: '/donar'
      path: '/donar'
      fullPath: '/donar'
      preLoaderRoute: typeof DonarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inversion': {
      id: '/inversion'
      path: '/inversion'
      fullPath: '/inversion'
      preLoaderRoute: typeof InversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resistencia': {
      id: '/resistencia'
      path: '/resistencia'
      fullPath: '/resistencia'
      preLoaderRoute: typeof ResistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ComunidadRoute: ComunidadRoute,
  CriptoRoute: CriptoRoute,
  DonarRoute: DonarRoute,
  EventosRoute: EventosRoute,
  IaRoute: IaRoute,
  InversionRoute: InversionRoute,
  LoginRoute: LoginRoute,
  PanelRoute: PanelRoute,
  PerfilRoute: PerfilRoute,
  RegistroRoute: RegistroRoute,
  ResistenciaRoute: ResistenciaRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
